import type { DecisionRule } from "@/types/decision";

export const DECISION_RULES: DecisionRule[] = [
  {
    useCase: "coding",
    usageLevel: "low",
    budgetMode: "cheapest",
    recommendedTool: "GitHub Copilot Free",
    recommendedModelId: "copilot-free",
    setupType: "Subscription",
    rationale: "Free Copilot tier covers 2000 completions/month — more than enough for light coding use with zero cost.",
    estimatedCost: 0,
    secondaryOption: "Cursor Free",
    affiliateKey: "github",
  },
  {
    useCase: "coding",
    usageLevel: "medium",
    budgetMode: "cheapest",
    recommendedTool: "DeepSeek V3 via API",
    recommendedModelId: "deepseek-v3",
    setupType: "API",
    rationale: "DeepSeek V3 delivers near-frontier coding quality at a fraction of GPT-4o cost. Ideal for moderate usage budgets.",
    estimatedCost: 4,
    secondaryOption: "GPT-4o Mini",
    affiliateKey: "deepseek",
  },
  {
    useCase: "coding",
    usageLevel: "high",
    budgetMode: "balanced",
    recommendedTool: "Cursor Pro",
    recommendedModelId: "cursor-pro",
    setupType: "Subscription",
    rationale: "For heavy daily coding, Cursor Pro's $20/month all-in-one subscription beats paying per token with a premium model.",
    estimatedCost: 20,
    secondaryOption: "Claude 3.5 Sonnet via API",
    affiliateKey: "cursor",
  },
  {
    useCase: "writing",
    usageLevel: "low",
    budgetMode: "cheapest",
    recommendedTool: "ChatGPT Free",
    recommendedModelId: "chatgpt-free",
    setupType: "Subscription",
    rationale: "Free ChatGPT covers occasional writing tasks with no cost commitment. Upgrade only when limits become a friction.",
    estimatedCost: 0,
    secondaryOption: "Gemini Free",
    affiliateKey: null,
  },
  {
    useCase: "writing",
    usageLevel: "medium",
    budgetMode: "balanced",
    recommendedTool: "Claude 3.5 Sonnet via API",
    recommendedModelId: "claude-3-5-sonnet",
    setupType: "API",
    rationale: "Claude Sonnet produces consistently strong writing output. Better quality-to-cost than GPT-4o for long-form content.",
    estimatedCost: 12,
    secondaryOption: "GPT-4o Mini",
    affiliateKey: "anthropic",
  },
  {
    useCase: "writing",
    usageLevel: "high",
    budgetMode: "cheapest",
    recommendedTool: "GPT-4o Mini via API",
    recommendedModelId: "gpt-4o-mini",
    setupType: "API",
    rationale: "For high-volume writing workflows, GPT-4o Mini keeps costs minimal while handling most content generation tasks reliably.",
    estimatedCost: 8,
    secondaryOption: "Gemini 1.5 Flash",
    affiliateKey: "openai",
  },
  {
    useCase: "research",
    usageLevel: "low",
    budgetMode: "balanced",
    recommendedTool: "Perplexity Pro",
    recommendedModelId: "perplexity-pro",
    setupType: "Subscription",
    rationale: "Perplexity Pro's $20/month covers real-time web research with citations. Best value for light but high-quality research needs.",
    estimatedCost: 20,
    secondaryOption: "ChatGPT Plus",
    affiliateKey: "perplexity",
  },
  {
    useCase: "research",
    usageLevel: "medium",
    budgetMode: "cheapest",
    recommendedTool: "DeepSeek V3 via API",
    recommendedModelId: "deepseek-v3",
    setupType: "API",
    rationale: "DeepSeek V3 handles research synthesis and summarization at a fraction of GPT-4o pricing with comparable output quality.",
    estimatedCost: 5,
    secondaryOption: "GPT-4o Mini",
    affiliateKey: "deepseek",
  },
  {
    useCase: "research",
    usageLevel: "high",
    budgetMode: "balanced",
    recommendedTool: "Gemini 1.5 Pro via API",
    recommendedModelId: "gemini-1-5-pro",
    setupType: "API",
    rationale: "Gemini 1.5 Pro's 2M context window makes it ideal for heavy research across large documents at competitive pricing.",
    estimatedCost: 18,
    secondaryOption: "Claude 3.5 Sonnet",
    affiliateKey: "google",
  },
  {
    useCase: "general",
    usageLevel: "low",
    budgetMode: "cheapest",
    recommendedTool: "ChatGPT Free",
    recommendedModelId: "chatgpt-free",
    setupType: "Subscription",
    rationale: "Free ChatGPT is the safest zero-cost starting point for general light AI usage.",
    estimatedCost: 0,
    secondaryOption: "Gemini Free",
    affiliateKey: null,
  },
  {
    useCase: "general",
    usageLevel: "medium",
    budgetMode: "balanced",
    recommendedTool: "GPT-4o Mini via API",
    recommendedModelId: "gpt-4o-mini",
    setupType: "API",
    rationale: "GPT-4o Mini handles the vast majority of general tasks at 97% less cost than GPT-4o with minimal quality trade-off.",
    estimatedCost: 6,
    secondaryOption: "DeepSeek V3",
    affiliateKey: "openai",
  },
  {
    useCase: "general",
    usageLevel: "high",
    budgetMode: "best-performance",
    recommendedTool: "ChatGPT Plus",
    recommendedModelId: "chatgpt-plus",
    setupType: "Subscription",
    rationale: "ChatGPT Plus at $20/month gives unlimited access to GPT-4o — the most predictable cost for heavy daily general use.",
    estimatedCost: 20,
    secondaryOption: "Claude Pro",
    affiliateKey: "openai",
  },
  {
    useCase: "productivity",
    usageLevel: "low",
    budgetMode: "cheapest",
    recommendedTool: "Gemini Free",
    recommendedModelId: "gemini-free",
    setupType: "Subscription",
    rationale: "Gemini Free handles light productivity tasks — email drafts, summarization, scheduling help — at zero cost.",
    estimatedCost: 0,
    secondaryOption: "ChatGPT Free",
    affiliateKey: null,
  },
  {
    useCase: "productivity",
    usageLevel: "medium",
    budgetMode: "balanced",
    recommendedTool: "GPT-4o Mini via API",
    recommendedModelId: "gpt-4o-mini",
    setupType: "API",
    rationale: "GPT-4o Mini is the most reliable productivity workhorse — fast, cheap, and good enough for email, docs, and automation.",
    estimatedCost: 5,
    secondaryOption: "Gemini 1.5 Flash",
    affiliateKey: "openai",
  },
  {
    useCase: "customer-support",
    usageLevel: "medium",
    budgetMode: "cheapest",
    recommendedTool: "Claude 3.5 Haiku via API",
    recommendedModelId: "claude-3-5-haiku",
    setupType: "API",
    rationale: "Claude Haiku provides quality customer support responses with Anthropic reliability at a budget-friendly cost per message.",
    estimatedCost: 8,
    secondaryOption: "GPT-4o Mini",
    affiliateKey: "anthropic",
  },
];

const FALLBACK_RULE: DecisionRule = {
  useCase: "general",
  usageLevel: "medium",
  budgetMode: "cheapest",
  recommendedTool: "GPT-4o Mini via API",
  recommendedModelId: "gpt-4o-mini",
  setupType: "API",
  rationale: "GPT-4o Mini is the safest default for any unspecified use case — cheap, capable, and widely supported.",
  estimatedCost: 6,
  secondaryOption: "DeepSeek V3",
  affiliateKey: "openai",
};

export function findDecisionRule(
  useCase: DecisionRule["useCase"],
  usageLevel: DecisionRule["usageLevel"],
  budgetMode: DecisionRule["budgetMode"]
): DecisionRule {
  const exact = DECISION_RULES.find(
    (r) => r.useCase === useCase && r.usageLevel === usageLevel && r.budgetMode === budgetMode
  );
  if (exact) return exact;

  const partialUseCase = DECISION_RULES.find(
    (r) => r.useCase === useCase && r.usageLevel === usageLevel
  );
  if (partialUseCase) return partialUseCase;

  const useCaseOnly = DECISION_RULES.find((r) => r.useCase === useCase);
  if (useCaseOnly) return useCaseOnly;

  return FALLBACK_RULE;
}
